version: '3.8'

services:
  mysqldb:
    image: mysql
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_USER=trybe
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=dronefeederdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=trybe
      - DB_PASSWORD=12345678
      - DB_NAME=dronefeederdb
      - DB_PORT=3306
    depends_on:
     - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db: