version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=dronefeederdb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=trybe
      - DB_PASSWORD=12345678
      - DB_NAME=dronefeederdb
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: