server:
  port: 8080
spring:
    datasource:
        username: root
        password: M0urinh4
        url: jdbc:mysql://localhost:3306/dronefeeder
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        #https://ia-tec-development.medium.com/lombok-e-spring-data-jpa-142398897733
    security.user:
        name: dronefeeder
        password: dronefeeder
        #https://www.baeldung.com/spring-boot-security-autoconfiguration


resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 10s
      failureRateThreshold: 10
  #instances:
    #estudantes:
      #baseConfig: default