server:
  port: 8080
spring:
    datasource:
        username: trybe
        password: 12345678
        url: jdbc:mysql://localhost:3306/dronefeeder
    security.user:
        name: dronefeeder
        password: dronefeeder
        #https://www.baeldung.com/spring-boot-security-autoconfiguration

resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 10s
      failureRateThreshold: 10
  #instances:
    #estudantes:
      #baseConfig: default