server:
  port: 8080
  #https://stackoverflow.com/questions/32927937/how-to-set-base-url-for-rest-in-spring-boot
  servlet.context-path: /dronefeeder
spring:
    datasource:
        username: trybe
        password: 12345678
        url: jdbc:mysql://localhost:3306/dronefeeder
    jpa:
        hibernate:
            ddl-auto: update
            enable_lazy_load_no_trans: true
        show-sql: true
        open-in-view: false
        #https://ia-tec-development.medium.com/lombok-e-spring-data-jpa-142398897733
    security.user:
        name: dronefeeder
        password: dronefeeder
        #https://www.baeldung.com/spring-boot-security-autoconfiguration
    main:
        allow-bean-definition-overriding: true
    #https://stackoverflow.com/questions/70036953/spring-boot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboo
    mvc:
        pathmatch.matching-strategy: ant_path_matcher


resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 10s
      failureRateThreshold: 10
  #instances:
    #estudantes:
      #baseConfig: default